Попов Ярослав, Расписание поездов
h31/ProgrammingLabTask1 pull request #19
Opened 2018-03-11 12:17 UTC by Ferrerohub

2018-03-15 08:17 UTC, h31 requested changes

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Files.java
> +    /*public static void addFileToDirectory(String name, String dir) {
Гигантское. Количество. Закомментированного кода. Не делайте так, это неаккуратно и излишне - все старые версии кода хранятся в гите и на GitHub-е.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Main.java
> +        if (seconds > 86399) {
Почему именно 86399? А не 86398, например?

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Main.java
> +    public static void main(String[] args) {
Два `main`-а в проекте, и оба пустые.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Main.java
> +        if (hour < 10) {
Три раза дублируется по сути один и тот же код.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Station.java
> +    public void setTable(Table table){
Не хватает стандартных методов: equals, hashCode, toString.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Table.java
> +public class Table {
Таблица? Для каких целей? Имена у классов, методов и переменных должны быть такими, чтобы сразу было понятно, зачем они нужны.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Table.java
> +    Map<String, String> Table = new LinkedHashMap<>();
Поля называются со строчной буквы.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Table.java
> +        result.append("Table:\n");
Если мы вызываем `toString` у объекта класса `Table`, то и так понятно, что мы получаем таблицу. Так что эта строчка лишняя.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Table.java
> +        for (String key : Table.keySet()) {
`Map` перебирается в цикле по-другому, через entries.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Table.java
> +    public boolean equals(Object obj){
Если реализуете `equals`, то делайте и `hashCode`. Такая договоренность в языке Java.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Table.java
> +        result.append("EndTable.\n");
См. предыдущий комментарий.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Trains.java
> +    /* public static Trains getTrainFromConsole(String text){
Опять закомментированный код.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Table.java
> +public class Table {
Всё, что умеет этот класс, вполне успешно делает и обычный `Map`. Стоит ли держать такой класс в проекте?

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Table.java
> +    public void addObjToTable(String name, String time) {
`ToTable` - и так понятно, куда добавляем. `Obj` - тоже понятно, что объект. Хотя это даже путает, потому что не любой объект подойдет, а только строка.

Замечание касается и других методов в классе.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Train.java
> +    public boolean equals(Object obj){
См. замечание про `hashCode` выше.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Train.java
> +        return "name= " + name+ ".\n" + "terminal= " + terminal+ "\n" + table;
Желательно не использовать перенос строки в `toString` без особой причины. `toString` используется в разных местах, и часто нам нужно уложиться в одну строку.

2018-03-15 08:17 UTC, h31 commented on src/main/resources/trains/trains.txt
> +name= First
Непонятные файлы, которые нигде кроме как в закомментированном коде не используются. Я обещал снижать оценку за мусор.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Trains.java
> +            result.append(train.toString()).append("####\n");
Аналогично Table.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Trains.java
> +        int division = 86400;
Магическое число. Я понимаю, что оно значит, но лучше это явно показать, вычисляя его.

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Trains.java
> +public class Trains {
Что нового добавляет этот класс относительно ArrayList?

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Table.java
> +    public boolean haveThis(String key){
`contains`

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Trains.java
> +        result.delete(length - 6, length);
Почему `- 6`??

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Trains.java
> +                int seconds = Integer.parseInt(table.get(station));
Зачем хранить данные в Map-е в виде строки, если вы всё равно обрабатываете их потом как число?

2018-03-15 08:17 UTC, h31 commented on src/main/java/ru/spbstu/kspt/task1/ru/spbstu/kspt/task1/Trains.java
> +                if ((seconds - Integer.parseInt(time) < division) && (seconds - Integer.parseInt(time) > 0)){
1) Если `time` - это число, то почему оно имеет тип String?
2) Если у нас 5 поездов, то нам обязательно 5 раз, в каждой итерации цикла парсить `time`?
3) Что будет, если `time` не является валидным числом?

2018-03-15 08:17 UTC, h31 commented on src/test/java/ru/spbstu/kspt/task1/TrainsTest.java
> +        put("Nevsky", "20000");
Почему 20000, а не 10000 или 50000?

2018-03-15 08:17 UTC, h31 commented on src/test/java/ru/spbstu/kspt/task1/TrainsTest.java
> +    Table tableResult = new Table(map);
У вас для добавления записи в таблицу есть отдельный метод. Задавая всё через Map, вы теряете в гибкости, и если вдруг захотите хранить данные как-нибудь ещё (например, в SQL-таблице или с другим типом данных), то придется писать гигантский конструктор для этого.

2018-03-15 08:17 UTC, h31 commented on src/test/java/ru/spbstu/kspt/task1/TrainsTest.java
> +        assertEquals(finded, trainResult4);
Название `trainResult4` ни о чем не говорит. Приходится листать на пол экрана вверх и смотреть.

2018-03-15 16:19 UTC, Ferrerohub commented on src/test/java/ru/spbstu/kspt/task1/TrainsTest.java
> +        put("Nevsky", "20000");
Так это время прибытия на станцию, я его в любом случае из головы буду брать

2018-03-15 18:15 UTC, h31 commented
Ярослав, вы мой документ читали? Зачем вы закрываете свой Pull Request (уже второй раз)? Почему вы единственный, кто закрывает свой PR?

Ставлю вам оценку 3. Я знаю, что вы хорошо пишете код, но этот раз вы не постарались. В следующих заданиях жду от вас большей вовлеченности в процесс, большей аккуратности при выполнении работ и соблюдения сроков выполнения.

2018-03-15 18:17 UTC, h31 commented on src/test/java/ru/spbstu/kspt/task1/TrainsTest.java
> +        put("Nevsky", "20000");
И часто вы в жизни задаете время в формате "20000 секунд"?

2018-03-15 18:19 UTC, h31 approved these changes

2018-03-23 17:09 UTC, h31 commented
Вижу, что исправили большинство замечаний. Повышаю оценку до "4-". Минус за то, что замечание к тестам всё ещё не исправлено.

2019-12-05 14:41 UTC, closed without merging